name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [synchronize, opened]

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate matrix
        id: generate-matrix        
        run: |
          echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT
  build:
    runs-on: ubuntu-latest
    needs: metadata
    strategy:
      matrix: ${{ fromJson(needs.metadata.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3

      - name: Run
        run: |
          echo "project=${{ matrix.project }}"
          echo "project=${{ matrix.config }}"
