name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [synchronize, opened]

jobs:
  metadata:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      matrix: ${{ steps.generate-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 0 indicates all history for all branches and tags.
      - name: Get changed directories
        id: diff_dirs
        uses: tj-actions/changed-files@eb136c70d4591e2ae2983990cc580db78ee8a278 # v32.1.2
        with:
          dir_names: true
          files_ignore: |
            .github
      - name: List all changed files
        run: |
          # 差分があったファイルのディレクトリ名を取得
          top_dir_names=()
          for file in ${{ steps.diff_dirs.outputs.all_changed_files }}; do
            top_dir_names+=($(echo $file | awk -F/ '{printf("%s",$1)}'))
          done
          echo "${top_dir_names[@]}"
          top_dir_names=($( printf "%s\n" "${top_dir_names[@]}" | sort -u ))
          echo "${top_dir_names[@]}"
          # service_name/ 以下のmodules以外のディレクトリを列挙
          for dir in "${top_dir_names[@]}"; do
            envs=$(ls -d ${dir}/*/ | grep -v modules || true)
            echo "${envs[@]}"
          done

      - name: Generate matrix
        id: generate-matrix
        run: |
          echo "matrix={\"include\":[{\"project\":\"foo\",\"config\":\"Debug\"},{\"project\":\"bar\",\"config\":\"Release\"}]}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: metadata
    strategy:
      matrix: ${{ fromJson(needs.metadata.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v3

      - name: Run
        run: |
          echo "project=${{ matrix.project }}"
          echo "project=${{ matrix.config }}"
